export const countries = [
  // United States at the top
  { code: "US", name: "United States of America" },
  
  // All other countries in alphabetical order
  { code: "AF", name: "Islamic Republic of Afghanistan" },
  { code: "AL", name: "Republic of Albania" },
  { code: "DZ", name: "People's Democratic Republic of Algeria" },
  { code: "AD", name: "Principality of Andorra" },
  { code: "AO", name: "Republic of Angola" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentine Republic" },
  { code: "AM", name: "Republic of Armenia" },
  { code: "AU", name: "Commonwealth of Australia" },
  { code: "AT", name: "Republic of Austria" },
  { code: "AZ", name: "Republic of Azerbaijan" },
  { code: "BS", name: "Commonwealth of The Bahamas" },
  { code: "BH", name: "Kingdom of Bahrain" },
  { code: "BD", name: "People's Republic of Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Republic of Belarus" },
  { code: "BE", name: "Kingdom of Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Republic of Benin" },
  { code: "BT", name: "Kingdom of Bhutan" },
  { code: "BO", name: "Plurinational State of Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Republic of Botswana" },
  { code: "BR", name: "Federative Republic of Brazil" },
  { code: "BN", name: "Brunei Darussalam" },
  { code: "BG", name: "Republic of Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Republic of Burundi" },
  { code: "CV", name: "Republic of Cabo Verde" },
  { code: "KH", name: "Kingdom of Cambodia" },
  { code: "CM", name: "Republic of Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Republic of Chad" },
  { code: "CL", name: "Republic of Chile" },
  { code: "CN", name: "People's Republic of China" },
  { code: "CO", name: "Republic of Colombia" },
  { code: "KM", name: "Union of the Comoros" },
  { code: "CD", name: "Democratic Republic of the Congo" },
  { code: "CG", name: "Republic of the Congo" },
  { code: "CR", name: "Republic of Costa Rica" },
  { code: "CI", name: "Republic of Côte d'Ivoire" },
  { code: "HR", name: "Republic of Croatia" },
  { code: "CU", name: "Republic of Cuba" },
  { code: "CY", name: "Republic of Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Kingdom of Denmark" },
  { code: "DJ", name: "Republic of Djibouti" },
  { code: "DM", name: "Commonwealth of Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Republic of Ecuador" },
  { code: "EG", name: "Arab Republic of Egypt" },
  { code: "SV", name: "Republic of El Salvador" },
  { code: "GQ", name: "Republic of Equatorial Guinea" },
  { code: "ER", name: "State of Eritrea" },
  { code: "EE", name: "Republic of Estonia" },
  { code: "SZ", name: "Kingdom of Eswatini" },
  { code: "ET", name: "Federal Democratic Republic of Ethiopia" },
  { code: "FJ", name: "Republic of Fiji" },
  { code: "FI", name: "Republic of Finland" },
  { code: "FR", name: "French Republic" },
  { code: "GA", name: "Gabonese Republic" },
  { code: "GM", name: "Republic of The Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Federal Republic of Germany" },
  { code: "GH", name: "Republic of Ghana" },
  { code: "GR", name: "Hellenic Republic" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Republic of Guatemala" },
  { code: "GN", name: "Republic of Guinea" },
  { code: "GW", name: "Republic of Guinea-Bissau" },
  { code: "GY", name: "Co-operative Republic of Guyana" },
  { code: "HT", name: "Republic of Haiti" },
  { code: "HN", name: "Republic of Honduras" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Republic of Iceland" },
  { code: "IN", name: "Republic of India" },
  { code: "ID", name: "Republic of Indonesia" },
  { code: "IR", name: "Islamic Republic of Iran" },
  { code: "IQ", name: "Republic of Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "State of Israel" },
  { code: "IT", name: "Italian Republic" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Hashemite Kingdom of Jordan" },
  { code: "KZ", name: "Republic of Kazakhstan" },
  { code: "KE", name: "Republic of Kenya" },
  { code: "KI", name: "Republic of Kiribati" },
  { code: "KP", name: "Democratic People's Republic of Korea" },
  { code: "KR", name: "Republic of Korea" },
  { code: "KW", name: "State of Kuwait" },
  { code: "KG", name: "Kyrgyz Republic" },
  { code: "LA", name: "Lao People's Democratic Republic" },
  { code: "LV", name: "Republic of Latvia" },
  { code: "LB", name: "Lebanese Republic" },
  { code: "LS", name: "Kingdom of Lesotho" },
  { code: "LR", name: "Republic of Liberia" },
  { code: "LY", name: "State of Libya" },
  { code: "LI", name: "Principality of Liechtenstein" },
  { code: "LT", name: "Republic of Lithuania" },
  { code: "LU", name: "Grand Duchy of Luxembourg" },
  { code: "MG", name: "Republic of Madagascar" },
  { code: "MW", name: "Republic of Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Republic of Maldives" },
  { code: "ML", name: "Republic of Mali" },
  { code: "MT", name: "Republic of Malta" },
  { code: "MH", name: "Republic of the Marshall Islands" },
  { code: "MR", name: "Islamic Republic of Mauritania" },
  { code: "MU", name: "Republic of Mauritius" },
  { code: "MX", name: "United Mexican States" },
  { code: "FM", name: "Federated States of Micronesia" },
  { code: "MD", name: "Republic of Moldova" },
  { code: "MC", name: "Principality of Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Kingdom of Morocco" },
  { code: "MZ", name: "Republic of Mozambique" },
  { code: "MM", name: "Republic of the Union of Myanmar" },
  { code: "NA", name: "Republic of Namibia" },
  { code: "NR", name: "Republic of Nauru" },
  { code: "NP", name: "Federal Democratic Republic of Nepal" },
  { code: "NL", name: "Kingdom of the Netherlands" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Republic of Nicaragua" },
  { code: "NE", name: "Republic of the Niger" },
  { code: "NG", name: "Federal Republic of Nigeria" },
  { code: "MK", name: "Republic of North Macedonia" },
  { code: "NO", name: "Kingdom of Norway" },
  { code: "OM", name: "Sultanate of Oman" },
  { code: "PK", name: "Islamic Republic of Pakistan" },
  { code: "PW", name: "Republic of Palau" },
  { code: "PA", name: "Republic of Panama" },
  { code: "PG", name: "Independent State of Papua New Guinea" },
  { code: "PY", name: "Republic of Paraguay" },
  { code: "PE", name: "Republic of Peru" },
  { code: "PH", name: "Republic of the Philippines" },
  { code: "PL", name: "Republic of Poland" },
  { code: "PT", name: "Portuguese Republic" },
  { code: "QA", name: "State of Qatar" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russian Federation" },
  { code: "RW", name: "Republic of Rwanda" },
  { code: "KN", name: "Federation of Saint Christopher and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Independent State of Samoa" },
  { code: "SM", name: "Republic of San Marino" },
  { code: "ST", name: "Democratic Republic of São Tomé and Príncipe" },
  { code: "SA", name: "Kingdom of Saudi Arabia" },
  { code: "SN", name: "Republic of Senegal" },
  { code: "RS", name: "Republic of Serbia" },
  { code: "SC", name: "Republic of Seychelles" },
  { code: "SL", name: "Republic of Sierra Leone" },
  { code: "SG", name: "Republic of Singapore" },
  { code: "SK", name: "Slovak Republic" },
  { code: "SI", name: "Republic of Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Federal Republic of Somalia" },
  { code: "ZA", name: "Republic of South Africa" },
  { code: "SS", name: "Republic of South Sudan" },
  { code: "ES", name: "Kingdom of Spain" },
  { code: "LK", name: "Democratic Socialist Republic of Sri Lanka" },
  { code: "SD", name: "Republic of the Sudan" },
  { code: "SR", name: "Republic of Suriname" },
  { code: "SE", name: "Kingdom of Sweden" },
  { code: "CH", name: "Swiss Confederation" },
  { code: "SY", name: "Syrian Arab Republic" },
  { code: "TJ", name: "Republic of Tajikistan" },
  { code: "TZ", name: "United Republic of Tanzania" },
  { code: "TH", name: "Kingdom of Thailand" },
  { code: "TL", name: "Democratic Republic of Timor-Leste" },
  { code: "TG", name: "Togolese Republic" },
  { code: "TO", name: "Kingdom of Tonga" },
  { code: "TT", name: "Republic of Trinidad and Tobago" },
  { code: "TN", name: "Republic of Tunisia" },
  { code: "TR", name: "Republic of Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Republic of Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom of Great Britain and Northern Ireland" },
  { code: "UY", name: "Oriental Republic of Uruguay" },
  { code: "UZ", name: "Republic of Uzbekistan" },
  { code: "VU", name: "Republic of Vanuatu" },
  { code: "VA", name: "Vatican City State" },
  { code: "VE", name: "Bolivarian Republic of Venezuela" },
  { code: "VN", name: "Socialist Republic of Vietnam" },
  { code: "YE", name: "Republic of Yemen" },
  { code: "ZM", name: "Republic of Zambia" },
  { code: "ZW", name: "Republic of Zimbabwe" }
]; 